<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/Einsum_Operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
B=np.array([[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]])
print(A.shape)
print(B.shape)

print("Matmul c=:\n")
print(np.matmul(A,B),"\n")

print("Einsum c=:\n")
print(np.einsum("ij,jk ->ik",A,B))

In [ ]:
 A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
B=np.array([[2,9,0,3],
            [3,6,8,-2],
            [1,3,5,0]])
print(A.shape)
print(B.shape)

print("Hardamond c=:\n")
print(A*B,"\n")

print("Einsum c=:\n")
print(np.einsum("ij,ij ->ij",A,B))

In [ ]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
print("Transposed A=:\n")
print(A.T,"\n")

print("Einsum A=:\n")
print(np.einsum("ij->ji",A))

In [33]:
A=np.array([[[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]],
            [[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]]])
B=np.array([[[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]],
           [[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]]])
print(A.shape)
print(B.shape)

print("Batch Multiplication c=:\n")
print(np.matmul(A,B),"\n")

print("Einsum c=:\n")
print(np.einsum("bij,bjk ->bik",A,B))

(2, 3, 4)
(2, 4, 5)
Batch Multiplication c=:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]] 

Einsum c=:

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]]


In [34]:
A=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])

print("Einsum A=:\n")
print(np.einsum("ij->i",A))

Einsum A=:

[15  5 10]


In [35]:
 A=np.random.randn(2,4,4,2)
 B=np.random.randn(2,4,4,1)

In [36]:
np.einsum("bcik,bcij -> bckj",B,A).shape

(2, 4, 1, 2)

In [26]:
import tensorflow as tf

In [38]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [3,4,5]],
    [[1,2,3],
     [3,4,5]],
    [[1,2,3],
     [3,4,5]]
])
print(tensor_three_d.shape)
x_exp=tf.expand_dims(tensor_three_d,axis=3)
print(x_exp.shape)
print(tf.squeeze(x_exp,axis=3))
print(tf.reshape(x_exp,[2,3,3]))

(3, 2, 3)
(3, 2, 3, 1)
tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [3 4 5]
  [1 2 3]]

 [[3 4 5]
  [1 2 3]
  [3 4 5]]], shape=(2, 3, 3), dtype=int32)


In [39]:
x=tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded=tf.expand_dims(x,axis=0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [40]:
x_squeezed=tf.squeeze(x_expanded,axis=0)
print(x_squeezed)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [42]:
t1=[[2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]]
t2=([[2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0]])
print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1,t2],axis=0)

(3, 4)
(3, 4)


<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 2,  6,  5,  2],
       [ 2, -2,  2,  3],
       [ 1,  5,  4,  0],
       [ 2,  9,  0,  3],
       [ 3,  6,  8, -2],
       [ 1,  3,  5,  0]], dtype=int32)>

In [43]:
tf.stack([t1,t2],axis=0)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 2,  6,  5,  2],
        [ 2, -2,  2,  3],
        [ 1,  5,  4,  0]],

       [[ 2,  9,  0,  3],
        [ 3,  6,  8, -2],
        [ 1,  3,  5,  0]]], dtype=int32)>

In [4]:
t=tf.constant([[1,2,3],
               [4,5,6]])
paddings=tf.constant([[1,1],
                    [2,3]])
tf.pad(t,paddings,"constant",constant_values=0)

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [7]:
params=tf.constant(['p0','p1','p2','p3','p4','p5'])
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [8]:
tf.gather(params,[0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [9]:
 indices=[[0]]
 params =[['a','b'],
          ['c','d']]
tf.gather_nd(params,indices)

<tf.Tensor: shape=(1, 2), dtype=string, numpy=array([[b'a', b'b']], dtype=object)>

In [10]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,5,-3],
    [4,5,6]
])
print(tensor_two_d.shape)

(3, 3)


In [12]:
tensor_two_d = [[
    [1,2,3],
    [3,],
    [4,5,6,7]
]]
tensor_ragged=tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[[1, 2, 3], [3], [4, 5, 6, 7]]]>


In [17]:
  print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [18]:
tf_sparse=tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]],values=[11,56],dense_shape=[5,6]
)
print(tf_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [20]:
tf.sparse.to_dense(tf_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

In [21]:
tensor_string=tf.constant(["hello","i am","a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am' b'a string'], shape=(3,), dtype=string)


In [25]:
tf.strings.join(tensor_string,separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am+a string'>

In [27]:
x=tf.constant([1,2])

In [29]:
x_var=tf.Variable(x,name='var1')

In [30]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [31]:
x_var.assign_sub([3,4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [33]:
with tf.device('GPU:0'):
  x_var=tf.Variable(0.2)
print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
