<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/Gradient_Decent_For_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df=pd.read_csv("insurance_d.csv")
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [ ]:
df.shape

(28, 3)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=20)

In [ ]:
len(x_train)

22

In [ ]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train_scaled['age']/100

x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test_scaled['age']/100

In [ ]:
x_train_scaled

,age,affordibility
18,0.19,0
25,0.54,1
23,0.45,1
22,0.40,1
21,0.26,0
5,0.56,1
24,0.50,1
19,0.18,1
14,0.49,1
17,0.58,1


In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')

])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=5000)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2502/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2503/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6818 - loss: 0.4883
Epoch 2504/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6818 - loss: 0.4882
Epoch 2505/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6818 - loss: 0.4882
Epoch 2506/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2507/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2508/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6818 - loss: 0.4881
Epoch 2509/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6818 - loss: 0.4880
Epoch 2510/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6818 - loss: 0.4880
Epoch 2511/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6

In [11]:
x_test_scaled


,age,affordibility
13,0.29,0
4,0.46,1
1,0.25,0
10,0.18,1
27,0.46,1
12,0.27,0


In [12]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[0.2111646 ],
       [0.7487071 ],
       [0.17427608],
       [0.36073586],
       [0.7487071 ],
       [0.19204609]], dtype=float32)

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [15]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [16]:
def prediction_function(age,affordability):
  weighted_sum=coef[0]*age+coef[1]*affordability+intercept
  return sigmoid(weighted_sum)
prediction_function(0.47,1)

<ipython-input-15-c72387dc9e07>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.7597215571264704

In [24]:
def log_loss(y_true,y_prediction):
  epsilon=1e-15
  y_predicted_new=[max(i,epsilon) for i in y_prediction]
  y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new=np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [25]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [41]:
class myNN:
  def __init__(self):
    self.w1=1
    self.w2=1
    self.bias=0

  def fit(self,x,y,epochs,loss_threshold):
    self.w1,self.w2,self.bias = self.gradient_descent(x['age'],x['affordibility'],y,epochs,loss_threshold)

  def predict(self,x_test):
    weighted_sum=self.w1*x_test['age']+self.w2*x_test['affordibility']+self.bias
    return sigmoid_numpy(weighted_sum)

  def gradient_descent(self,age,affordability,y_true,epochs,loss_thresold):
      w1=w2=1
      bias=0
      rate=0.5
      n=len(age)
      for i in range(epochs):
        weighted_sum=w1*age+w2*affordability+bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))
        bias_d=np.mean(y_predicted-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*bias_d

        if i%50==0:
             print(f'epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')

        if(loss<=loss_thresold):
           break
      return w1,w2,bias

In [42]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000,0.4631)

epoch:0,w1:0.9899044631276738,w2:0.9569405919425348,bias:-0.07899372792977674,loss:0.645879853336323
epoch:1,w1:0.9839956437241003,w2:0.9213120476683795,bias:-0.14783282323721283,loss:0.6306399722613678
epoch:2,w1:0.9818392584739325,w2:0.8924082047006104,bias:-0.20758236411882589,loss:0.6194338742775531
epoch:3,w1:0.9829714996091098,w2:0.8694378697530099,bias:-0.25936841626475815,loss:0.6112638943448379
epoch:4,w1:0.9869327312511998,w2:0.8515941187585563,bias:-0.3042992643556669,loss:0.6053096946136317
epoch:5,w1:0.9932909005876579,w2:0.8381042430709594,bias:-0.3434115278383518,loss:0.6009323224120783
epoch:6,w1:1.0016552381106507,w2:0.828260552915365,bias:-0.3776393247774238,loss:0.5976547897595172
epoch:7,w1:1.0116822714409655,w2:0.821435592496283,bias:-0.407801431258409,loss:0.5951326106822025
epoch:8,w1:1.0230764951373805,w2:0.817086248135435,bias:-0.4346007971785253,loss:0.5931233031450338
epoch:9,w1:1.035587744835964,w2:0.81475080344,bias:-0.45863157249275605,loss:0.5914595419655

(np.float64(4.239223037614316),
 np.float64(1.2513317462202243),
 np.float64(-2.2294236940715884))

In [43]:
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [44]:
custommodel=myNN()
custommodel.fit(x_train_scaled,y_train,epochs=500,loss_threshold=0.4631)

epoch:0,w1:0.9899044631276738,w2:0.9569405919425348,bias:-0.07899372792977674,loss:0.645879853336323
epoch:50,w1:1.709461534136061,w2:0.9788070573819416,bias:-0.9598603700641541,loss:0.5544131238551514
epoch:100,w1:2.5004831931182125,w2:1.1071645304905515,bias:-1.394181454447879,loss:0.5209783874963289
epoch:150,w1:3.222577955990388,w2:1.1786670576324696,bias:-1.7517820560121107,loss:0.49468107114612336
epoch:200,w1:3.8769337082171416,w2:1.2270961918891738,bias:-2.0609667436236645,loss:0.47354879778661074


In [45]:
coef,intercept

(array([[5.942501 ],
        [1.3994231]], dtype=float32),
 array([-3.041245], dtype=float32))

In [46]:
custommodel.predict(x_test_scaled)

,0
13,0.268932
4,0.725508
1,0.236924
10,0.446448
27,0.725508
12,0.252592


In [47]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[0.2111646 ],
       [0.7487071 ],
       [0.17427608],
       [0.36073586],
       [0.7487071 ],
       [0.19204609]], dtype=float32)