<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/tf_Data_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
daily_sales_numbers = [21,22,-108,31,-1,32,34,31]

In [4]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [6]:
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
-108
31
-1
32
34
31


In [7]:
for sales in tf_dataset.take(3):
  print(sales.numpy())

21
22
-108


In [8]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
31
32
34
31


In [9]:
tf_dataset = tf_dataset.map(lambda x: x*90)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1890
1980
2790
2880
3060
2790


In [10]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

1890
1980
2880
2790
3060
2790


In [11]:
for sales_batch in tf_dataset.batch(4):
  print(sales_batch.numpy)

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1890, 1980, 2880, 3060], dtype=int32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2790, 2790], dtype=int32)>>


In [13]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*90).shuffle(2).batch(4)
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

[1890 1980 2880 3060]
[2790 2790]
