<a href="https://colab.research.google.com/github/ADITI9981/Deep_Learning/blob/main/Word_Embedding_Using_Keras_Embedding_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[5, 11]

In [4]:
vocab_size = 30
encoded_review = [one_hot(d,vocab_size) for d in reviews]
print(encoded_review)

[[17, 19], [5, 11], [14, 6], [8, 2, 2], [12, 7, 9], [19, 19], [10, 7, 28], [28, 11], [28, 1], [19, 5]]


In [6]:
max_length=3
padded_review = pad_sequences(encoded_review,maxlen=max_length,padding='post')
print(padded_review)

[[17 19  0]
 [ 5 11  0]
 [14  6  0]
 [ 8  2  2]
 [12  7  9]
 [19 19  0]
 [10  7 28]
 [28 11  0]
 [28  1  0]
 [19  5  0]]


In [13]:
embeded_vector_size=5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_shape=(max_length,), name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [14]:
x=padded_review
y=sentiment

In [15]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 166 (664.00 B)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [16]:
model.fit(x,y,epochs=50,verbose=0)

In [17]:
loss,accuracy=model.evaluate(x,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 385ms/step - accuracy: 1.0000 - loss: 0.6158


1.0

In [21]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [22]:
weights[17]

array([-0.01131126,  0.02351169,  0.09227107,  0.01594432,  0.03489006],
      dtype=float32)